#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || ipconfig getifaddr bridge0 2>/dev/null || true)
if [ -z "$IP" ]; then
  echo "Could not detect LAN IP. Connect to Wi-Fi or hotspot and try again."
  exit 1
fi

API_URL="http://${IP}:8000"
cat > .env.development.local <<EOF
# Auto-generated by scripts/start-lan.sh — do not commit
EXPO_PUBLIC_API_URL=${API_URL}
EOF

echo "API URL: ${API_URL}"
echo "Phone must be on the same network (Wi-Fi or hotspot)."
echo ""

exec npx expo start --lan --clear
