#!/usr/bin/env bash
# Exposes Metro (8081) and the FastAPI backend (8000) via Cloudflare quick tunnels.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared is not installed. Run: brew install cloudflared"
  exit 1
fi

wait_for_tunnel_url() {
  local log_file=$1
  for _ in $(seq 1 45); do
    local url
    url=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$log_file" | head -1 || true)
    if [ -n "$url" ]; then
      echo "$url"
      return 0
    fi
    sleep 1
  done
  return 1
}

METRO_LOG=$(mktemp)
API_LOG=$(mktemp)
cleanup() {
  rm -f "$METRO_LOG" "$API_LOG"
  kill "$METRO_PID" "$API_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

echo "Starting Cloudflare tunnels..."
cloudflared tunnel --url "http://127.0.0.1:8081" >"$METRO_LOG" 2>&1 &
METRO_PID=$!
cloudflared tunnel --url "http://127.0.0.1:8000" >"$API_LOG" 2>&1 &
API_PID=$!

METRO_URL=$(wait_for_tunnel_url "$METRO_LOG") || {
  echo "Metro tunnel failed. Log:"
  cat "$METRO_LOG"
  exit 1
}
API_URL=$(wait_for_tunnel_url "$API_LOG") || {
  echo "API tunnel failed. Log:"
  cat "$API_LOG"
  exit 1
}

cat > .env.development.local <<EOF
# Auto-generated by scripts/start-cloudflare.sh — do not commit
EXPO_PUBLIC_API_URL=${API_URL}
EOF

echo ""
echo "Metro tunnel: $METRO_URL"
echo "API tunnel:   $API_URL"
echo ""
echo "Scan the QR code in Expo Go."
echo ""

export EXPO_PACKAGER_PROXY_URL="$METRO_URL"
exec npx expo start --lan --clear
