/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProveRouteImport } from './routes/prove'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as GymRouteImport } from './routes/gym'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveRoute = ProveRouteImport.update({
  id: '/prove',
  path: '/prove',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/gym': typeof GymRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/prove': typeof ProveRoute
  '/schedule': typeof ScheduleRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/gym': typeof GymRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/prove': typeof ProveRoute
  '/schedule': typeof ScheduleRoute
  '/social': typeof SocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/gym': typeof GymRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/prove': typeof ProveRoute
  '/schedule': typeof ScheduleRoute
  '/social': typeof SocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/gym'
    | '/onboarding'
    | '/progress'
    | '/prove'
    | '/schedule'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/gym'
    | '/onboarding'
    | '/progress'
    | '/prove'
    | '/schedule'
    | '/social'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/gym'
    | '/onboarding'
    | '/progress'
    | '/prove'
    | '/schedule'
    | '/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  GymRoute: typeof GymRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  ProveRoute: typeof ProveRoute
  ScheduleRoute: typeof ScheduleRoute
  SocialRoute: typeof SocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prove': {
      id: '/prove'
      path: '/prove'
      fullPath: '/prove'
      preLoaderRoute: typeof ProveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  GymRoute: GymRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  ProveRoute: ProveRoute,
  ScheduleRoute: ScheduleRoute,
  SocialRoute: SocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
